### ISSUE TITLE
v5.0.0 napi-v6 instead of napi-v3

### ISSUE THREAD

**Issue by Kepro** [journeyapps/node-sqlcipher#61]
when using with cordova-electron 2.0.0 that is using electron 10.1.2
https://cordova.apache.org/announcements/2020/10/02/cordova-electron-release-2.0.0.html

it will build napi-v6 instead of napi-v3, any idea how to fix it?
```
Uncaught (in promise) Error: Cannot find module 'C:\Projects\insight-assess-mobile-app\node_modules\@journeyapps\sqlcipher\lib\binding\napi-v3-win32-x64\node_sqlite3.node'
Require stack:
- C:\Projects\insight-assess-mobile-app\node_modules\@journeyapps\sqlcipher\lib\sqlite3-binding.js
- C:\Projects\insight-assess-mobile-app\node_modules\@journeyapps\sqlcipher\lib\sqlite3.js
```

**Comment by Kepro** [comment]
when I update electron to 11 it just crash with blank page and with disconnected dev tools

**Comment by 1111mp** [comment]
I also encountered the same problem
